#!/bin/sh

# Run with `sh build`
# Run result automatically with `sh build -r`

runcmd="java -classpath Class Main"
compcmd="javac -d Class `find Source -type f -name \"*.java\"`"

argv=($@)
argc=${#@}

# flags
flag_run=0
flag_noconfirm=0

for (( i = 0; i < $argc; i++ )); do 
case "${argv[$i]}" in
    "-r"|"--run")
        [ "$flag_run" = 0 ] &&
            flag_run=1
        continue
    ;;

    "-y"|"--noconfirm"|"--yes")
        [ "$flag_noconfirm" = 0 ] &&
            flag_noconfirm=1
        continue
    ;;

    *)
        echo "No match"
        continue
    ;;
esac
done

echo "Compile Command: $compcmd"

[ $flag_run ] &&
echo "    Run Command: $runcmd"

# [ $flag_noconfirm ] &&
    $compcmd &&
    $runcmd
